### PR TITLE
Add support for bitcode iOS SDK

### PR DESCRIPTION
**Pull request by petergam**
This is a request for you to enabled bitcode for the iOS SDK. I realise that this way of requesting it is a little odd but I thought it was worth a shot!

> Bitcode is an intermediate representation of a compiled program. Apps you upload to iTunes Connect that contain bitcode will be compiled and linked on the App Store. Including bitcode will allow Apple to re-optimize your app binary in the future without the need to submit a new version of your app to the store.
> 
> Note: For iOS apps, bitcode is the default, but optional. If you provide bitcode, all apps and frameworks in the app bundle need to include bitcode. For watchOS apps, bitcode is required

Apps using your framework must currently disable bitcode since MobilePay-AppSwitch-SDK has it disabled. Apple will most likely require bitcode in the future so enabling it is the right choice going forward.

### CODE REVIEW

**Comment by PelleRavn** [comment]
I asked about this back in december. The answer at that time was that a part of the MobilePay SDK is the OpenSSL SDK, and it doesn't support Bitcode. I'm not aware if that has changed in OpenSSL in the last 6 months, but I think the MobilePay SDK team want to support Bitcode if they could - so guess it will come when it's all their dependencies supports Bitcode.

**Comment by petergam** [comment]
Thanks for providing that information @PelleRavn 

Compiling OpenSSL with bitcode enabled should be supported, I dont know which script the MobilePay team uses to compile OpenSSL but if there are using https://github.com/x2on/OpenSSL-for-iPhone it should work out of the box.

I really hope the team will consider looking into this again.

**Comment by petergam** [comment]
Any update on this? Maybe from @duytv?

**Comment by sn3ek** [comment]
Please provide a new build with bitcode enabled.

**Comment by simonbs** [comment]
Please provide a version of your SDK with bitcode enabled. Currently all apps that support MobilePay will have to disable bitcode which is unheard of.

**Comment by bigfishtoddslivewire** [comment]
I'll see if it works for me. Let's hope

**Comment by christiankm** [comment]
Thanks for your comments. We have added support for Bitcode in version 1.8.1.
Feel free to open a PR for any wishes or send me a DM. Alternatively please send your wishes to developer@mobilepay.dk.

**Comment by simonbs** [comment]
@christiankm It looks like the latest version (2.2.0) doesn't have bitcode enabled. Is it intentional that it was disabled again?

**Comment by christiankm** [comment]
Hi @simonbs,
Sorry for not being your message. I will ask the responsible people about this :)

**Comment by christiankm** [comment]
@simonbs It seems that Bitcode *is* enabled. What errors are you seeing?
If installing via CocoaPods, it should help if you can remove any `-Objc` linker flags in your project.

**Pull request closed without merging**
